name: Test  Action

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
        
      - name: test_ci
        uses: arjunbuildbear/buildbear_x_action@main
            
        with: 
          network: |
            [
              {
                "chainId": 12
              },
              {
                "chainId": 59144
              }
            ]
          deploy-command: "make exe"
          buildbear-token: "a"
          working-directory: "app"  
         
