name: Test My Action

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Show Forge version
        run: forge --version

      - name: bb_action_ci
        uses: arjunbuildbear/test2@33
            
        with: 
          network: |
            [
              {
                "chainId": 1,
                "blockNumber": 10000
              }
            ]
          deploy-command: "make exe"
          buildbear-token: "BB"
          slack-webhook-url: "https://hooks.slack.com/services/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"
